version: '2'
services:
  amakein-uii:
    build:
      context: "./"
     
    ports:
      - "3000:3000"
    container_name: amakein-uii
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    