version: '3'
services:
  amakein-uie:
    build:
      context: "./"
     
    ports:
      - "3000:3000"
    container_name: amakein-uie
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    